### PR TITLE
mixins.modid.json -> modid.mixins.json

### PR DESCRIPTION
**Pull request by florensie**
Following conventions from FabricMC.

### CODE REVIEW

**Comment by TheGlitch76** [comment]
`mixins.modid.json` is for MCDev integration in IDEA.

**Comment by florensie** [comment]
How does that work?

**Comment by TheGlitch76** [comment]
It only detects the file if it leads with `mixins.` for some reason

**Comment by florensie** [comment]
Seems like an issue with mcdev then to me.

edit: it seems to work fine for me 
image

**Pull request closed without merging**
